FROM apache/airflow:2.9.3

# OS packages as root
USER root
RUN apt-get update && apt-get install -y --no-install-recommends \
    postgresql-client \
 && rm -rf /var/lib/apt/lists/*

# Install Python deps **as airflow** (no --user)
USER airflow
COPY requirements.txt /requirements.txt
RUN pip install --no-cache-dir -U pip && \
    pip install --no-cache-dir -r /requirements.txt